name: "When updates are pushed or the defined schedule is triggered, scan the container and application for vulnerabilities"

on:

  push:

  schedule:
    - cron: '0 0 * * *'

jobs:

  scan-and-report-vulnerabilities:
    
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Build image
        run: | 
          docker build --tag "073045235439.dkr.ecr.us-east-1.amazonaws.com/test:v2" \
            --file ./src/Dockerfile
            
      - name: Run Trivy vulnerability scanner
        run: |
          curl -L https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.tar.gz | tar xvzf - contrib trivy
          chmod 755 trivy
          mv trivy /usr/local/bin/trivy
          trivy image --format template --template "@contrib/sarif.tpl" --output trivy-results.sarif 073045235439.dkr.ecr.us-east-1.amazonaws.com/test:v2

      - name: Upload container results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: trivy-results.sarif
